# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/jahirsaiyed/Multica"
  version "0.1.26-TEST-9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-9/multica_darwin_amd64.tar.gz"
      sha256 "b911e885717487e71579c1fcf7891f167f77f48fa8f9e41197adcf3c2d6b55b8"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-9/multica_darwin_arm64.tar.gz"
      sha256 "05abc2cb205b9a1a3e3ef01709db7eaf4e60f4e25f8bd0ec2eaedf510a945ffc"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-9/multica_linux_amd64.tar.gz"
      sha256 "3dcd5d339ce31d880b6bd9a32f4a57236419a7bef27d99b0706724f40fc11647"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-9/multica_linux_arm64.tar.gz"
      sha256 "07a61f2bed5663205e256f0438b7ba164b985d365a2756f51c6b14149d7fc908"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
