# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/jahirsaiyed/Multica"
  version "0.1.26-TEST-4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-4/multica_darwin_amd64.tar.gz"
      sha256 "63f495842259717042127b79ac950da43dea89e41f0ee929eccaacfc9b51c92d"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-4/multica_darwin_arm64.tar.gz"
      sha256 "7b6e328152fc79e4e603353e2efb7ca51ba25e391184b1426e3c3a77727fc464"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-4/multica_linux_amd64.tar.gz"
      sha256 "fb3317f17129c5b0ab2c3b165c6880e26fa78e909912dbfecbc387d118e8833d"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahirsaiyed/Multica/releases/download/v0.1.26-TEST-4/multica_linux_arm64.tar.gz"
      sha256 "d118f0aa8218ef0a76f9dfea54fb517ea197f73926874d621da8ca7a1c7a73dd"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
